package mocks

import "github.com/myteksi/go/commons/util/test/methodman/examples/approach1/bookingsdk"
import "github.com/stretchr/testify/mock"

// SDK is an autogenerated mock type for the SDK type
type SDK struct {
	mock.Mock
}

// GetBookingState provides a mock function with given fields: bookingCode
func (_m *SDK) GetBookingState(bookingCode string) (*bookingsdk.BookingInfo, error) {
	ret := _m.Called(bookingCode)

	var r0 *bookingsdk.BookingInfo
	if rf, ok := ret.Get(0).(func(string) *bookingsdk.BookingInfo); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingsdk.BookingInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
